[package]
name = "monolith-storage"
description = "Persistent and ephemeral state storage for Monolith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
monolith-identity.workspace = true

[lints]
workspace = true
